refactor to use k8s jobs and cleanup

diff --git a/reapers/kubernetes b/reapers/kubernetes
--- a/reapers/kubernetes
+++ b/reapers/kubernetes
@@ -2,14 +2,31 @@
 set -a
 ORIGINAL_JOB=$JOB
 
+query_pods()
+{
+  kubectl get pods -a --selector=service=$JOB "$@" 2> /dev/null
+}
+
+oldest_pod(){  
+  query_pods -o=custom-columns=STATUS:.status.startTime,NAME:.metadata.name \
+   | sort | head -n1 | awk '{ print $5 }'
+}
+
 reap()
 {
   source /etc/default/$JOB
-  START=$(kubectl get pod $pod -o template -t '{{.metadata.creationTimestamp}}' 2> /dev/null)
-  kubectl delete pod $pod > /dev/null
+  # Might want to use .metadata.creationTimestamp
+  START=$(kubectl get job $pod -o=jsonpath={.status.startTime} 2> /dev/null)
+  END=$(kubectl get job $pod -o=jsonpath={.status.completionTime} 2> /dev/null)
+  if [[ "$END" == "<nil>" ]]; then #Failure to launch results in nil completion
+    END=$(date +"%Y-%m-%d %H:%M:%S %z %Z")
+  fi
+
+  kubectl delete job $job_name > /dev/null
   echo "[$JOB] Reaping @ [$OUTPUT] @ $END"
 
   if [ $ALERTER ]; then
+      export POD_NAME=$pod
       . /app/alerters/$ALERTER
   fi
 }
@@ -17,22 +34,23 @@ reap()
 # If job set. Reap that job
 # Itereate over all finished jobs
 if [ -z "$JOB" ] ; then
-  all_jobs=($(kubectl get pods -a -l jobrunner --no-headers 2> /dev/null | cut -d ' ' -f1))
+  all_jobs=($(kubectl get jobs -o=jsonpath='{.items[*].metadata.name}' 2> /dev/null))
 else
-  all_jobs=($(echo $JOB | tr '[:upper:]' '[:lower:]'))
+  all_jobs=($(kubectl get jobs --selector=service=${JOB} -o=jsonpath='{.items[*].metadata.name}' 2> /dev/null))
 fi
 
-for pod in "${all_jobs[@]}"
+for job_name in "${all_jobs[@]}"
 do
   #Get the original job name
-  JOB=$(kubectl get pod $pod -o template --template '{{index .metadata.labels "jobrunner"}}' 2> /dev/null)
+  JOB=$(kubectl get jobs $job_name -o=jsonpath={.metadata.labels.service} 2> /dev/null)
   if [ -f "/etc/default/$JOB" ] ; then
-    STATUS=$(kubectl get pod $pod -o template --template '{{.status.phase}}' 2> /dev/null)
+    pod=$(oldest_pod)
+    STATUS=$(kubectl get pod $pod -o=jsonpath={.status.phase} 2> /dev/null)
     case $STATUS in
       Pending|Running )
         
-        ERRORS=$(kubectl get pod invalidcommand -o template  --template '{{with $x:= index .status.containerStatuses 0}}{{$x.state.waiting}}{{end}}' 2> /dev/null); DERPY=$?
-        if [ $DERPY -eq 0 ]; then
+        ERRORS=$(kubectl get pod $pod -o=jsonpath='{.status.containerStatuses[0].state.waiting.message}' 2> /dev/null); ERROR_CMD=$?
+        if [ $ERROR_CMD -eq 0 ]; then
           OUTPUT="[${JOB}] - Unknown pending status - ${ERRORS}"
           STATUS="Error in Pending"
           EXIT_CODE=98
@@ -42,12 +60,12 @@ do
         
       ;;
       Succeeded|Failed )
-        EXIT_CODE=$(kubectl get pod $pod -o template --template '{{with $x:= index .status.containerStatuses 0}}{{$x.state.terminated.exitCode}}{{end}}')
+        EXIT_CODE=$(kubectl get pod $pod -o=jsonpath='{.status.containerStatuses[0].state.terminated.exitCode}')
         if ! [ "$EXIT_CODE" -eq "$EXIT_CODE" ] 2> /dev/null ; then
           OUTPUT="Invalid EXIT_CODE [$EXIT_CODE]"
           EXIT_CODE=99
         else
-          REASON=$(kubectl get pod $pod -o template --template '{{with $x:= index .status.containerStatuses 0}}{{$x.state.terminated.reason}}{{end}}')
+          REASON=$(kubectl get pod $pod -o=jsonpath='{.status.containerStatuses[0].state.terminated.reason}')
           if [[ "$REASON" == "OOMKilled" ]]; then
             EXIT_CODE=137
           fi
diff --git a/runners/kubernetes b/runners/kubernetes
--- a/runners/kubernetes
+++ b/runners/kubernetes
@@ -2,50 +2,30 @@
 # Set KUBERNETES_MASTER to the URL of your cluster example http://kubemaster:8080
 export KUBERNETES_MASTER
 NODE_SELECTOR=${NODE_SELECTOR:=""}
+PULL_POLICY=${PULL_POLICY:=""}
 
-addImagePullPolicy() {
-  if [ -n "$PULL_POLICY" ]; then
-      IMAGE_PULL_POLICY=""s/imagePullPolicy\":\ \"\"/imagePullPolicy\":\ \"${PULL_POLICY}\"/""
-      sed -i "$IMAGE_PULL_POLICY" k8s_pod/${JOB,,}-pod.yaml
-  fi  
-}
-
-addNodeSelector() {
-  IFS=',' read -a VALUES <<< $NODE_SELECTOR
-  NODE_SELECTOR="{"
-
-  for var in ${VALUES[@]}
-  do
-    KEY="\"${var%=*}\""
-    VALUE="\"${var#*=}\""
-    NODE_SELECTOR="$NODE_SELECTOR $KEY:$VALUE,"
-  done
-  NODE_SELECTOR="${NODE_SELECTOR%,*}"
-  NODE_SELECTOR="$NODE_SELECTOR }"
-  SELECTOR="/\"containers\": \[/i\"nodeSelector\": $NODE_SELECTOR,"
-  sed -i "$SELECTOR" k8s_pod/${JOB,,}-pod.yaml
-}
-
-addLabel() {
-  SELECTOR="/\"labels\": {/,/}/c\\\"labels\": {\n\"jobrunner\":\"$JOB\"\n\}"
-  sed -i "$SELECTOR" k8s_pod/${JOB,,}-pod.yaml
-}
-
-. /app/processor/reap && unset EXIT_CODE
-
-JOB_LOWERCASE=$(echo $JOB | tr '[:upper:]' '[:lower:]')
-sed -e "0,/$JOB/{s/$JOB/$JOB_LOWERCASE/}" /app/compose/$JOB.yaml > /app/compose/$JOB.lowercase.yaml
-compose2kube -compose-file /app/compose/$JOB.lowercase.yaml -output-dir k8s_pod > /dev/null
-rm /app/compose/$JOB.lowercase.yaml
-
-addImagePullPolicy
-addNodeSelector
-addLabel
-
-if kubectl create -f k8s_pod/${JOB,,}-pod.yaml > /dev/null ; then
-  rm k8s_pod/${JOB,,}-pod.yaml
+. /app/processor/reap
+if [[ "$EXIT_CODE" -eq 98 ]]; then
+  echo 'Container creation error'
+  return
 else
-  OUTPUT="Could not create pod. $OUTPUT"
+  unset EXIT_CODE
+fi
+
+
+if [[ -z $(kubectl get pods --selector=service=${JOB} 2> /dev/null ) ]]; then
+  compose2kube \
+    -compose-file /app/compose/$JOB.yaml \
+    -pull-policy="${PULL_POLICY}" \
+    -node-selector="${NODE_SELECTOR}" \
+    -output-dir k8s_${JOB} > /dev/null
+  OUTPUT=$(kubectl create -f k8s_${JOB}); RESULT=$?
+  rm -rf k8s_${JOB}
+
+  if [ $RESULT -ne 0 ]; then
+    EXIT_CODE=101
+  fi
+else
   if [ "$IGNORE_OVERRUN" = true ] ; then
     echo "[${JOB}] - IGNORING OVERRUN - will not alert"
     EXIT_CODE=0
@@ -56,7 +36,7 @@ else
 fi
 
 #Ensure the pod is actually registered. Avoids a possible race condition
-until kubectl get pods $JOB_LOWERCASE &> /dev/null
+until kubectl get jobs --selector=service=${JOB} &> /dev/null
 do
   sleep 0.1
 done
@@ -72,7 +52,8 @@ else
     . /app/processor/reap
   done
 
-  kubectl logs -f $JOB_LOWERCASE &
+  POD_NAME=$(kubectl get pods --selector=service=$JOB -o=jsonpath='{.items[*].metadata.name}')
+  kubectl logs -f $POD_NAME &
 
   while [ -z "$EXIT_CODE" ]
   do
